import XCTest

final class CodeUITests: XCTestCase {

    @MainActor func testCodeHomeFilterAndHostHooksPreserveList() {
        let app = XCUIApplication()
        app.launch()
        app.buttons["sidebar.open"].tap()
        app.buttons.containing(.staticText, identifier: "Code").firstMatch.tap()
        XCTAssertTrue(app.buttons["code.add-device"].waitForExistence(timeout: 3))
        capture("code-home")
        app.buttons["code.filter"].tap()
        XCTAssertTrue(app.buttons["Needs input"].waitForExistence(timeout: 2))
        capture("code-filter")
        app.buttons["Needs input"].tap()
        XCTAssertTrue(app.buttons["code.session.map"].exists)
        XCTAssertFalse(app.buttons["code.session.design"].exists)
        app.buttons["code.filter"].tap()
        app.buttons["All"].tap()
        XCTAssertTrue(app.buttons["code.session.design"].exists)
        app.buttons["code.add-device"].tap()
        XCTAssertTrue(app.buttons["code.remote.copy"].waitForExistence(timeout: 2))
        capture("code-add-device")
        app.buttons["sheet.close.Set up remote control"].tap()
        app.buttons["code.new-session"].tap()
        XCTAssertTrue(app.buttons["code.draft.back"].waitForExistence(timeout: 2))
        app.buttons["code.draft.back"].tap()
        XCTAssertTrue(app.buttons["code.session.design"].exists)
        app.buttons["sidebar.open"].tap()
        app.buttons.containing(.staticText, identifier: "New session").firstMatch.tap()
        XCTAssertTrue(app.buttons["composer.voice"].waitForExistence(timeout: 2))
    }

    @MainActor func testCodeDraftModelBranchPermissionAndBackPreserveDraft() {
        let app = XCUIApplication()
        app.launchArguments = ["--code-new-session"]
        app.launch()
        XCTAssertTrue(app.buttons["code.draft.model"].waitForExistence(timeout: 3))
        XCTAssertFalse(app.buttons["code.draft.send"].isEnabled)
        capture("code-new-session")
        app.buttons["code.draft.model"].tap()
        capture("code-models")
        app.buttons["code.model.effort"].tap()
        capture("code-effort")
        app.buttons["code.effort.Ultracode"].tap()
        app.buttons["sheet.close.Select model"].tap()
        XCTAssertTrue(app.buttons["code.draft.model"].label.contains("Ultracode"))
        app.buttons["code.draft.repository"].tap()
        capture("code-repository-menu")
        app.buttons["Change branch"].tap()
        XCTAssertTrue(app.buttons["code.branch.feature"].waitForExistence(timeout: 2))
        capture("code-branches")
        app.buttons["code.branch.feature"].tap()
        XCTAssertTrue(app.buttons["code.draft.repository"].label.contains("sample_branch"))
        app.buttons["code.draft.attach"].tap()
        capture("code-context")
        app.buttons["code.context.permission"].tap()
        capture("code-permission")
        app.buttons["code.permission.Plan"].tap()
        XCTAssertTrue(app.buttons["code.context.permission"].label.contains("Plan"))
        app.buttons["sheet.close.Add context"].tap()
        let draft = app.textFields["code.draft.text"]
        draft.tap()
        // Typing before the keyboard finishes appearing can drop keystrokes.
        XCTAssertTrue(app.keyboards.firstMatch.waitForExistence(timeout: 3))
        draft.typeTextVerified("Keep this local task")
        XCTAssertTrue(app.buttons["code.draft.send"].isEnabled)
        app.buttons["code.draft.send"].tap()
        XCTAssertEqual(draft.value as? String, "Keep this local task")
        app.buttons["code.draft.back"].tap()
        app.buttons["code.new-session"].tap()
        XCTAssertEqual(app.textFields["code.draft.text"].value as? String, "Keep this local task")
    }
    @MainActor func testCodeEnvironmentCancelAndRepositorySelection() {
        let app = XCUIApplication()
        app.launchArguments = ["--code-new-session"]
        app.launch()
        app.buttons["code.draft.environment"].tap()
        XCTAssertTrue(app.buttons["code.environment.create"].waitForExistence(timeout: 2))
        capture("code-environments")
        app.buttons["code.environment.create"].tap()
        XCTAssertTrue(app.buttons["code.environment.network"].waitForExistence(timeout: 2))
        capture("code-environment-create")
        XCTAssertFalse(app.buttons["code.environment.submit"].isEnabled)
        app.buttons["code.environment.network"].tap()
        // Released iOS 27 labels menu items "Title, subtitle", so match on the title prefix.
        let fullAccess = app.buttons.matching(NSPredicate(format: "label BEGINSWITH %@", "Full network access"))
            .firstMatch
        XCTAssertTrue(fullAccess.waitForExistence(timeout: 2))
        capture("code-environment-network")
        fullAccess.tap()
        XCTAssertTrue(app.buttons["code.environment.network"].label.contains("Full network access"))
        app.buttons["sheet.close.New cloud environment"].tap()
        app.buttons["code.environment.cloud"].tap()
        XCTAssertTrue(app.buttons["code.draft.environment"].label.contains("Cloud"))
        app.buttons["code.draft.repository"].tap()
        app.buttons["Change repository"].tap()
        XCTAssertTrue(app.buttons["code.repository.library"].waitForExistence(timeout: 2))
        capture("code-repositories")
        app.buttons["code.repository.library"].tap()
        app.buttons["sheet.close.Repositories (1)"].tap()
        XCTAssertTrue(app.buttons["code.draft.repository"].label.contains("BookLibrary"))
    }

    @MainActor func testCodeConnectorPermissionsRemainLocal() {
        let app = XCUIApplication()
        app.launchArguments = ["--code-new-session"]
        app.launch()
        app.buttons["code.draft.attach"].tap()
        XCTAssertTrue(app.buttons["code.context.connectors"].waitForExistence(timeout: 3))
        app.buttons["code.context.connectors"].tap()
        XCTAssertTrue(app.switches["code.connectors.discovery"].waitForExistence(timeout: 2))
        capture("code-connectors")
        app.buttons["code.connector.design"].tap()
        capture("code-connector-tools")
        app.buttons["code.connector.all-tools"].tap()
        capture("code-tool-permission")
        app.buttons["code.tool.permission.Blocked"].tap()
        XCTAssertTrue(app.buttons["code.connector.all-tools"].label.contains("Never"))
        app.buttons["sheet.close.Design tools"].tap()
        app.buttons["sheet.close.Connectors"].tap()
        app.buttons["sheet.close.Add context"].tap()
        XCTAssertFalse(app.buttons["code.draft.send"].isEnabled)
    }
}
